//! Project scaffolding. Given a [`ValidatedModule`], lay out a Cargo
//! project under the workspace whose `src/lib.rs` is the scaffold-owned
//! prelude + (optional) capability shim + the validated paste, plus a
//! pinned-empty `Cargo.toml` (zero deps — the v1 compile-time-RCE
//! defense) and a vendored zero-dep `json` module.
//!
//! All filesystem paths are jailed under [`GUARDIAN_ROOT`] (a sub-tree of
//! the tool-layer workspace jail). The `embra-guardian` crate must NOT
//! depend on `embra-brain`, so the jail logic is duplicated here (it is
//! ~20 pure lines, mirrors `engineering.rs::resolve_workspace_path`).

use std::path::{Path, PathBuf};

use crate::abi;
use crate::error::GuardianError;
use crate::validator::ValidatedModule;

/// Guardian's writable sub-tree of `/embra/workspace` (DATA, persists
/// reboots). `tools/<name>/` per tool; `target/` + `cargo-home/` shared.
pub const GUARDIAN_ROOT: &str = "/embra/workspace/.guardian";

const PRELUDE_SRC: &str = include_str!("guest/prelude.rs");
const JSON_SRC: &str = include_str!("guest/json.rs");

/// Scaffold-owned safe wrapper for the `guardian::http_get` host import.
/// Appended only when the tool declared the `http_get` capability.
const HOST_HTTP_MOD: &str = r#"
mod host {
    use alloc::string::String;
    #[link(wasm_import_module = "guardian")]
    extern "C" {
        #[link_name = "http_get"]
        fn guardian_http_get(url_ptr: u32, url_len: u32) -> u64;
    }
    /// Guardian-mediated HTTPS GET. Returns a JSON string:
    /// `{"ok":true,"status":u16,"url":..,"content_type":..,"body":..}`
    /// or `{"ok":false,"error":..}`. The host enforces https-only,
    /// RFC1918/SSRF, optional allowlist, size + content-type caps.
    pub fn http_get(url: &str) -> String {
        let packed = unsafe { guardian_http_get(url.as_ptr() as u32, url.len() as u32) };
        let ptr = (packed >> 32) as usize;
        let len = (packed & 0xffff_ffff) as usize;
        if ptr == 0 || len == 0 {
            return String::from("{\"ok\":false,\"error\":\"host returned no data\"}");
        }
        let bytes = unsafe { core::slice::from_raw_parts(ptr as *const u8, len) };
        String::from_utf8_lossy(bytes).into_owned()
    }
}
"#;

const CARGO_TOML_TMPL: &str = r#"# Generated by embra-guardian-v1 — DO NOT EDIT.
# Zero dependencies is the v1 compile-time-RCE defense (no build.rs /
# proc-macro can run on the live OS). Capabilities are host imports.
[package]
name = "{NAME}"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]

[profile.release]
opt-level = "z"
lto = true
panic = "abort"
strip = true
codegen-units = 1
"#;

const CARGO_CONFIG: &str = r#"[build]
target = "wasm32-unknown-unknown"

[term]
quiet = true

[net]
offline = true
"#;

/// Concrete paths produced by [`scaffold`].
#[derive(Debug, Clone)]
pub struct ScaffoldPaths {
    pub project: PathBuf,
    pub manifest: PathBuf,
    pub lib_rs: PathBuf,
    /// Where `cargo build --release --target wasm32-unknown-unknown`
    /// drops the cdylib (target dir is overridden via env in `build`).
    pub artifact_name: String,
}

fn valid_name(name: &str) -> bool {
    let b = name.as_bytes();
    (3..=40).contains(&name.len())
        && b[0].is_ascii_lowercase()
        && b.iter().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || *c == b'_')
}

/// Per-tool project dir, jailed under `base` (`base` is normally
/// [`GUARDIAN_ROOT`]; tests pass a tempdir). The validated name is
/// `[a-z0-9_]{3,40}` so it cannot contain `/` or `..` — the join stays
/// inside `base/tools/`.
pub fn safe_tool_dir(base: &Path, name: &str) -> Result<PathBuf, GuardianError> {
    if !valid_name(name) {
        return Err(GuardianError::PathDenied(format!(
            "tool name `{name}` is not [a-z][a-z0-9_]{{2,39}}"
        )));
    }
    let dir = base.join("tools").join(name);
    // Defense in depth: the computed path must remain under base/tools.
    let anchor = base.join("tools");
    if !dir.starts_with(&anchor) {
        return Err(GuardianError::PathDenied(format!(
            "resolved path {dir:?} escapes {anchor:?}"
        )));
    }
    Ok(dir)
}

/// Assemble the full guest `src/lib.rs`: scaffold-owned prelude, optional
/// capability shim, then the validated paste. Pure — unit-tested.
pub fn assemble_lib_rs(m: &ValidatedModule) -> String {
    let mut s = String::with_capacity(PRELUDE_SRC.len() + m.source.len() + 1024);
    s.push_str(PRELUDE_SRC);
    if m.caps.iter().any(|c| c == abi::CAP_HTTP_GET) {
        s.push_str(HOST_HTTP_MOD);
    }
    s.push_str("\n// ===== validated guardian-tool paste (scaffold-wrapped) =====\n");
    s.push_str(&m.source);
    if !m.source.ends_with('\n') {
        s.push('\n');
    }
    s
}

/// Materialize the project under `base`. Idempotent: overwrites
/// `Cargo.toml` / `src/*` so a redefine or a reconcile rebuild is clean.
pub fn scaffold(base: &Path, m: &ValidatedModule) -> Result<ScaffoldPaths, GuardianError> {
    let project = safe_tool_dir(base, &m.name)?;
    let src = project.join("src");
    let cargo_dir = project.join(".cargo");
    for d in [&project, &src, &cargo_dir] {
        std::fs::create_dir_all(d).map_err(|e| GuardianError::Io(e.to_string()))?;
    }

    let manifest = project.join("Cargo.toml");
    write(&manifest, &CARGO_TOML_TMPL.replace("{NAME}", &m.name))?;
    write(&cargo_dir.join("config.toml"), CARGO_CONFIG)?;
    write(&src.join("json.rs"), JSON_SRC)?;
    let lib_rs = src.join("lib.rs");
    write(&lib_rs, &assemble_lib_rs(m))?;

    Ok(ScaffoldPaths {
        project,
        manifest,
        lib_rs,
        artifact_name: format!("{}.wasm", m.name),
    })
}

fn write(path: &Path, contents: &str) -> Result<(), GuardianError> {
    std::fs::write(path, contents).map_err(|e| {
        GuardianError::Io(format!("{}: {e}", path.display()))
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn module(caps: Vec<String>) -> ValidatedModule {
        ValidatedModule {
            name: "web_search".into(),
            description: "d".into(),
            input_schema: json!({"type":"object","properties":{}}),
            caps,
            source: "// guardian-tool: web_search\nfn run(input: &str) -> String { String::new() }\n"
                .into(),
        }
    }

    #[test]
    fn assemble_has_prelude_json_and_paste() {
        let s = assemble_lib_rs(&module(vec![]));
        assert!(s.contains("#![no_std]"));
        assert!(s.contains("mod json;"));
        assert!(s.contains("pub extern \"C\" fn guardian_run"));
        assert!(s.contains("// guardian-tool: web_search"));
        assert!(s.contains("fn run(input: &str)"));
        assert!(!s.contains("mod host {"), "no host shim without caps");
    }

    #[test]
    fn assemble_adds_host_shim_only_with_cap() {
        let s = assemble_lib_rs(&module(vec!["http_get".into()]));
        assert!(s.contains("mod host {"));
        assert!(s.contains("wasm_import_module = \"guardian\""));
        assert!(s.contains("link_name = \"http_get\""));
    }

    #[test]
    fn tool_dir_is_jailed() {
        let base = Path::new("/tmp/gbase");
        let ok = safe_tool_dir(base, "web_search").unwrap();
        assert_eq!(ok, Path::new("/tmp/gbase/tools/web_search"));
        for bad in ["../escape", "a/b", "Bad", "..", "x", "with-dash"] {
            assert!(safe_tool_dir(base, bad).is_err(), "must reject {bad}");
        }
    }

    #[test]
    fn scaffold_writes_files() {
        let base = std::env::temp_dir().join(format!(
            "guardian-scaffold-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        let p = scaffold(&base, &module(vec!["http_get".into()])).unwrap();
        assert!(p.manifest.exists());
        assert!(p.lib_rs.exists());
        assert!(p.project.join(".cargo/config.toml").exists());
        assert!(p.project.join("src/json.rs").exists());
        let toml = std::fs::read_to_string(&p.manifest).unwrap();
        assert!(toml.contains("name = \"web_search\""));
        assert!(toml.contains("crate-type = [\"cdylib\"]"));
        assert!(toml.contains("[dependencies]\n\n[profile.release]"), "deps must be empty");
        assert_eq!(p.artifact_name, "web_search.wasm");
        let _ = std::fs::remove_dir_all(&base);
    }
}
